### ISSUE TITLE
Disable APM fails to skip amp version after opening the second link on the same page of results

### ISSUE THREAD

**Issue by atc891** [AdguardTeam/DisableAMP#100]
Использую последнюю версию скрипта через расширение userscripts на ios 18.0.1, safari, гугл, вкладка новостей. При переходах по ссылкам на overclockers.ru и hi-tech.mail.ru не всегда переводит с amp. Также когда нажимаю в safari на кнопку возврата на предыдущую страницу и потом перехожу по другой ссылке из результатов поиска гугла, то перевод с amp не срабатывает, начинает работать только после того как обновлю страницу 2-3 раза или перейду на следующую страницу результатов поиска.

**Comment by Versty** [comment]
@atc891 Добрый день! 
Мы проверили работу юзерскрипта на наших устройствах, и, к сожалению, не удалось повторить описанную проблему. 

Если у вас включены другие юзерскрипты и расширения в Сафари, пожалуйста отключите их, и проверьте повторно.

**Comment by atc891** [comment]
отключил все расширения, кроме userscripts, и оставил включенным только скрипт disable amp, [записал видео](https://drive.google.com/file/d/1zZt0N3rLQIxKuY5PFp-yguBOKrW5YaWs/view?usp=sharing), amp-страницы не поддерживают темные режимы сайтов.

пока решил проблему включением опции открытия ссылок из гугла в новой вкладке, выполняется в настройках поиска. На ios эта опция в настройках мобильной версии сайта не отображается, чтобы ее включить нужно перейти на настольную версию сайта.

**Comment by Versty** [comment]
@atc891 Спасибо, видео помогло разобраться и повторить проблему. 
Дополню изначальное сообщениями подробными шагами воспроизведения, их будут использовать разработчики при поиске решения для исправления проблемы.
