### ISSUE TITLE
Libero Quotidiano wrong link

### ISSUE THREAD

**Issue by 0xrxL** [AdguardTeam/DisableAMP#102]
1. Open Google
2. Search "Libero Quotidiano" (website: www.liberoquotidiano.it)
3. Open a news of it
4. A "page not found" message will be show.

<details><summary>Screenshot_20241020_084706_Samsung Internet Beta</summary>

![Screenshot_20241020_084706_Samsung Internet Beta](https://github.com/user-attachments/assets/814e160a-5fbd-44a2-b778-60b5017f9622)

</details>

**Comment by 0xrxL** [comment]
https://github.com/user-attachments/assets/8b2890bb-73de-4d15-9fe6-52c5ffc6de28

**Comment by 0xrxL** [comment]
> @0xrxL what version of DisableAMP are you using?

1.0.49

**Comment by jellizaveta** [comment]
Hi there! Changes in the new version, don't forget to update the userscript if it didn't update automatically. Thanks for your contribution!
