### ISSUE TITLE
Infinite reloading on innogyan.in

### ISSUE THREAD

**Issue by safethumb** [AdguardTeam/DisableAMP#103]
If mobile browser, it realods infinitely on this site.
[https://innogyan.in/2024/10/18/oneplus-13-now-available-for-pre-sale-with-exclusive-benefits/?amp=1](https://innogyan.in/2024/10/18/oneplus-13-now-available-for-pre-sale-with-exclusive-benefits/?amp=1)
* This also happens if I remove "amp=1".

I'm using firefox-android131.0.3, Violentmonkey.

**Comment by jellizaveta** [comment]
Hi! The issue with infinite reloading has been solved in the new version(1.0.52), don't forget to update the userscript if it didn't update automatically. Thanks for your contribution!
