### ISSUE TITLE
Some websites accessible from Google Images are broken

### ISSUE THREAD

**Issue by 0xrxL** [AdguardTeam/DisableAMP#104]
The last version of `Disable AMP` cannot correctly fetch the webpage link, if the website is accessed from images tab. Example:

1) Use the keysearch: Samsung S24 review.

2) Open images tab on google search.

3) Try to open the review of `Business Standard` website:

<details>
  <summary>Screenshot 1</summary>

  ![Screenshot_20241111_103537_Samsung Internet Beta](https://github.com/user-attachments/assets/94bbb0b3-dbbb-4ec1-bd7b-68cf3c2aac04)

</details>

4) What you'll see will be an empty AMP preview:

<details>
  <summary>Screenshot 2</summary>

  ![Screenshot_20241111_104114_Samsung Internet Beta](https://github.com/user-attachments/assets/943f4b5c-c3af-42fb-a666-8ecc42b062d0)

</details>

**Comment by 0xrxL** [comment]
IndiaToday.in show the same behaviour.

**Comment by jellizaveta** [comment]
@0xrxL Hello. Unfortunately, cannot reproduce, all pages open in a new tab. What script version are you using?

**Comment by 0xrxL** [comment]
> @0xrxL Hello. Unfortunately, cannot reproduce, all pages open in a new tab. What script version are you using?

1.0.52

**Comment by jellizaveta** [comment]
@0xrxL Hello again! Thanks for reporting that bug. The new version, `1.0.56`, has some changes that should fix it! Thanks for taking the time to provide the steps to reproduce the bug. Is everything ok with the new version on your side?

**Comment by 0xrxL** [comment]
> @0xrxL Hello again! Thanks for reporting that bug. The new version, `1.0.56`, has some changes that should fix it! Thanks for taking the time to provide the steps to reproduce the bug. Is everything ok with the new version on your side?

Hi.

I tried both IndiaToday and Business Standard websites from Google Image, and everything works flawlessly now.

Thanks.
