### ISSUE TITLE
sedaily.com

### ISSUE THREAD

**Issue by Githubmaniak** [AdguardTeam/DisableAMP#105]
https://m.sedaily.com/NewsViewAmp/2DGTEUS876

https://m.sedaily.com/NewsView/2DGTEUS876

Disable AMP does not work on sedaily.com.

userscript manager: AdGuard
OS: Android 14
Browser: Mozilla Firefox 132

**Comment by jellizaveta** [comment]
Hi. The issue has been fixed in the new version 1.0.58. Thank you for your contribution!
