### ISSUE TITLE
`m.economictimes.com`

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/DisableAMP#106]
DisableAMP should redirect from
https://m.economictimes.com/news/international/us/oshi-no-ko-season-3-when-will-new-episodes-air-and-who-is-returning/amp_articleshow/113989324.cms
to
https://m.economictimes.com/news/international/us/oshi-no-ko-season-3-when-will-new-episodes-air-and-who-is-returning/articleshow/113989324.cms

**Comment by jellizaveta** [comment]
Hi. The issue has been fixed in the new version 1.0.58. Thank you for your contribution!
