### ISSUE TITLE
Internapoli.it infinite reloading

### ISSUE THREAD

**Issue by 0xrxL** [AdguardTeam/DisableAMP#107]
1. Open a news from dedicated shelf on Google.

<details>
  <summary>Screenshot 1 </summary>

  ![Screenshot_20241119_133935_Samsung Internet Beta](https://github.com/user-attachments/assets/7bcdfe51-e045-476b-8b48-e03559645492)
  
</details>

2. You'll experience an infinite reloading.

**Comment by jellizaveta** [comment]
Hello,
I just wanted to let you know the new version is now available with the changes. I really appreciate your input, and I'm happy to say that the bug should be fixed!
