### ISSUE TITLE
AMP slideshow

### ISSUE THREAD

**Issue by Oizaro** [AdguardTeam/DisableAMP#23]
Hi.

I've noticed that on certain site of AMP slideshow "[this](https://i.ibb.co/RPvJhXJ/20200527-142109.jpg)" some websites don't load, because "data-amp-cur" element is missing.

Could you check? Thanks

**Comment by tvinzz** [comment]
please, provide the links to these websites

**Comment by Oizaro** [comment]
@tvinzz 

There's no specific links, you should search "coronavirus" (for example) on Google and try to open one of last news on AMP slideshow at the top of page. Some reload the Google page and some others instead work and redirect to the news page.

**Comment by Oizaro** [comment]
@tvinzz 

**This is what happen on some slideshow news**

<img src="https://i.ibb.co/Ydghy4B/Immagine.png">

**Comment by Oizaro** [comment]
https://github.com/AdguardTeam/DisableAMP/pull/24

**Comment by Oizaro** [comment]
@tvinzz 

Give a look to this code inside my repository... https://github.com/Oizaro/DisableAMP/blob/master/src/disable-amp.js

To correct the bug I crafting a link to AMP preview page, and after I got the standard link from the top bar inside of this page. In this way I'm always sure (theoretically) to make a correct redirect to the normal page, because this one will be directly generated from Google.

**Comment by tvinzz** [comment]
I will test it

**Comment by Oizaro** [comment]
Thanks... Meawhile I try to improve it (maybe removing the click event listener).

**Comment by Oizaro** [comment]
@tvinzz 

I've also made some other changes to remove observeDomChanges function and click eventlistener. Now the code seems to be more faster. :D

**Comment by Oizaro** [comment]
@tvinzz 

After several tests and changes, maybe I've finalize the code:

https://github.com/AdguardTeam/DisableAMP/pull/25

**Comment by Oizaro** [comment]
@tvinzz 

After several tests and changes, maybe I have reach the final code form:

https://github.com/AdguardTeam/DisableAMP/pull/26

**Comment by tvinzz** [comment]
I detected the problem with slideshow, but unfortunately your solution doesn't work.
for example try to find in google this article https://www.rtl.fr/actu/bien-etre/coronavirus-l-epidemie-en-ile-de-france-est-derriere-nous-assure-un-medecin-7800571810

**Comment by Oizaro** [comment]
@tvinzz 

Two things:

1) Your Google searching platform localization is Russian or French? In this way I can find a proxy to make a better tests.

2) I searched your link on google and opened it without problems (look here: https://gifyu.com/image/uL9U). Have you tried the latest code I linked yesterday? It has several fixes that make it working in every circumstance

**Comment by Oizaro** [comment]
<b>PR UPDATE: I have found some pages that doesn't use https:// protocol on AMP slideshow. So I have extended the script logic to these.</b>
