### ISSUE TITLE
return condition break icon removing

### ISSUE THREAD

**Issue by Oizaro** [AdguardTeam/DisableAMP#27]
Happens on some sites of AMP sideshow with empty URL:

<img src="https://i.ibb.co/3dBvLtg/Screenshot-20200613-134742-Samsung-Internet.jpg">

**Comment by Oizaro** [comment]
@tvinzz Hide AMP icon function should be moved before the return condition to retrieve the correct URL.

**Comment by Oizaro** [comment]
https://github.com/AdguardTeam/DisableAMP/pull/29

**Comment by tvinzz** [comment]
> @tvinzz Hide AMP icon function should be moved before the return condition to retrieve the correct URL.

no, it shouldn't

**Comment by Oizaro** [comment]
@tvinzz @ameshkov 

Why close this bug report? The problem occurs on some news and some not. Look here:

<img src="https://i.ibb.co/19YTckw/Screenshot-20200616-042514-Samsung-Internet.jpg">

**Comment by tvinzz** [comment]
Because we remove amp icons only for elements with fixed links.

**Comment by Oizaro** [comment]
Ok so it's a choice to keep the icon on elements without normal url.

**Comment by tvinzz** [comment]
yes, it's to avoid any misunderstandings.
if element still linked to amp page, it has the amp icon.
and for this case the `ampRedirect` function was added.

**Comment by Oizaro** [comment]
Technically it is possible to get a normal url from an amp page, but you have to use another approach (like that of my previous script, which I am still using) that must be tested on various sites.

**Comment by tvinzz** [comment]
yes, even `ampRedirect` function was not the best solution, because if google will change something in amp pages layout, this function will make a lot of troubles for the users. but it works good for the moment.
