### ISSUE TITLE
AMP preview page shown after click on news and redirect to wrong page

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/DisableAMP#28]
<img src="https://s7.gifyu.com/images/SmartSelect_20200613-135838_Gallery.gif">

<b>Wrong news:</b>

<img src="https://s7.gifyu.com/images/Screen_Recording_20200616-004432_1.gif">

**Comment by Oizaro** [comment]
@tvinzz Maybe I'll be repetitive, but getting the link from the amp preview page is the best solution at the moment. Seems strange that it doesn't work for you.

https://github.com/AdguardTeam/DisableAMP/pull/26
