### ISSUE TITLE
Not working anymore on Chromium Browsers

### ISSUE THREAD

**Issue by jenabaivab** [AdguardTeam/DisableAMP#36]
I am on the latest Adguard Nightly for Android and the extension just seems to have stopped working. I tried with Samsung Internet Beta, Vivaldi Snapshot and Chrome. None of them were able to override the amp pages. Atleast the other browsers didn't have the AMP logo, Samsung Internet Beta had the logo beside the search results too. 
I tried using Firefox, and I didn't face this issue over there. There was no logo, no AMP. 
Something wrong with Chromium browsers only.

**Comment by tvinzz** [comment]
@jenabaivab, can you please provide more details: links, screenshots, etc.
For the moment I detected the problem with amp icons only in Vivaldi browser on Android. But redirection works properly.

**Comment by jenabaivab** [comment]
@tvinzz 

https://drive.google.com/file/d/1dayBr7-8Gmi53ce8Uy_uQndn0_cb0Kac/view?usp=drivesdk

Is this clear or should I gather more?

**Comment by tvinzz** [comment]
@jenabaivab
fixed. please try [v1.0.10-beta](https://github.com/AdguardTeam/DisableAMP/releases/tag/v1.0.10-beta)

**Comment by jenabaivab** [comment]
@tvinzz very sorry for the stupid question, but how do I install it? I downloaded the ZIP file and extracted it.

**Comment by tvinzz** [comment]
in AdGuard for Android choose Menu -> Settings -> Extensions
delete old version of script and add new (click on "+ New extension" and choose "Browse..")

![image](https://user-images.githubusercontent.com/15062885/96040963-c8556680-0e73-11eb-9dbe-29a82a5271aa.png)

**Comment by jenabaivab** [comment]
@tvinzz already tried that, but whenever I select the .ZIP file, it always says "Error while parsing the userscript". 
Is there some specific file inside the extracted folder that I should select after I click on browse?

**Comment by tvinzz** [comment]
yes, you need only `disable-amp.user.js`

**Comment by jenabaivab** [comment]
@tvinzz There is no such file in the .zip archive.

**Comment by ameshkov** [comment]
Use this link to install the beta version: https://userscripts.adtidy.org/beta/disable-amp/1.0/disable-amp.user.js

**Comment by jenabaivab** [comment]
Yes, it's fixed. Both the logo and URL redirection are fixed as per my checks on multiple browsers.
Thank you so much!

**Comment by tvinzz** [comment]
you're welcome
