### ISSUE TITLE
Форвардинг на источник

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/DisableAMP#39]
Добрый день,

добавьте, пожалуйста, автоматический форвардинг на исходную страницу. Так это реализовано в этом скрипте:
https://greasyfork.org/ru/scripts/411827-avoid-yandex-turbo

Спасибо.

**Comment by ameshkov** [comment]
@tvinzz а можешь посмотреть и добавить к нам? Давно пора Yandex Turbo тоже захватить.

**Comment by ammnt** [comment]
Работает! Ура, ребята вы лучшие!
