### ISSUE TITLE
Adguard program for Android not blocked Turbo-pages Yandex

### ISSUE THREAD

**Issue by biomednet** [AdguardTeam/DisableAMP#49]
Андроид 11, AdGuard 4.0 nightly 23 (64) программа, локальный VPN (без рута).
Не блокирует (не "вычищает") переходы на турбо-страницы Яндекса. 
Браузер Samsung Browser (стабильная версия).
Скрипт против AMP не работает. AdGuard Extra включен.

Android 11, program AdGuard 4.0 nightly 23 (64) non-root, local VPN.
Not blocked redirect to yandex-turbo pages.
Browser Samsung Browser (stable).
Inclusion of the script anti-AMP and AdGuard Extra has no effect.

**Comment by d0x360** [comment]
Well I tested it in every way I could think and it did nothing.   I don't understand... It's supposed to strip whatever you say from a url but it can't even do the simple "/amp"

**Comment by tvinzz** [comment]
@biomednet, @d0x360 
Please, check the latest version of Disable-AMP (v1.0.23) and AdGuard (v4.0 nightly 24). Works fine for me on Android in Chrome browser for disabling amp links and redirecting turbo pages.

**Comment by d0x360** [comment]
That's the version I'm running.  Where is it stripping amp out?  Is it just search results or is it working on Google now's news feed as well?

**Comment by tvinzz** [comment]
@d0x360, yes, I checked right now, google news as well.

**Comment by d0x360** [comment]
Well wth... I'm even on a new phone so it's the perfect testing ground.

I just can't get rid of amp and it's driving me insane.

Do you have any user rules for amp?

**Comment by tvinzz** [comment]
@d0x360, no, unfortunately, just user rules are not enough to disable amp.
We will test Disable-AMP userscript more carefully to detect problem.
Could you please provide few amp links you are visiting.

**Comment by d0x360** [comment]
Here are a few from the Google now feed.

https://www.gamespot.com/amp-articles/halo-mccs-next-beta-includes-a-file-share-system-improved-custom-games-browser/1100-6495713/

https://www.forbes.com/sites/paultassi/2021/08/30/destiny-2s-season-of-the-lost-had-a-truly-wild-first-week/amp/

https://www.androidpolice.com/2021/08/30/apps-from-amazon-and-whatsapp-hit-500-million-installs-on-the-play-store/?amp

https://www.phonearena.com/amp/news/galaxy-fold-3-drop-test-destruction-how-much-can-it-survive_id134655

https://www.dsogaming.com/mods/red-dead-redemption-2-gets-an-ai-enhanced-hd-texture-pack-that-improves-all-weapons/amp/


Hopefully that helps.  I made a user rule to remove /amp/ but it never
worked except oddly on techradar.com

**Comment by d0x360** [comment]
![Screenshot_20210830-181558_Nova7](https://user-images.githubusercontent.com/14056857/131413043-9e587178-18d0-4e55-8ad6-b81e4742f706.jpg)

**Comment by tvinzz** [comment]
@d0x360
You are welcome to try 1.0.24 dev version of Disable-AMP userscript
[disable-amp.beta.zip](https://github.com/AdguardTeam/DisableAMP/files/7083290/disable-amp.beta.zip)

**Comment by tvinzz** [comment]
Disable-AMP [v1.0.24](https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.user.js) released

**Comment by d0x360** [comment]
I'll give it a shot and report back

**Comment by d0x360** [comment]
Ok so it does definitely work better.  It removed amp from most things I tested.  One link that it didn't work on is tje following...

https://www.ign.com/articles/cyberpunk-2077-modders-hired-cd-projekt-various-projects?amp=1

Other than that it worked on everything in my Google now feed.  I didn't refresh the page to check more links because I have a meeting in a couple min but this is definitely a huge improvement over the previous revision.

**Comment by tvinzz** [comment]
@d0x360, thank you, it will be fixed soon in v1.0.26

**Comment by d0x360** [comment]
My pleasure, if I can help make Adguard better even in a small way it makes
all the time I spend in the app tweaking and writing rules to test worth
it... Although my wife might disagree 😜

**Comment by tvinzz** [comment]
Disable-AMP [v1.0.26](https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.user.js) released.
Fixed amp redirect for links like https://www.ign.com/articles/cyberpunk-2077-modders-hired-cd-projekt-various-projects?amp=1.
I'm closing this issue. If the problem occurs again, please feel free to reopen.
