### ISSUE TITLE
Back button does not bring you to the search result

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/DisableAMP#5]
When the AMP removal extension is enabled in Adguard for Android 3.2.150, the "back" button shows incorrect behavior. 

Steps to reproduce:
1. Open Google.com and search for something that leads to AMP links in search result
2. Click on an AMP link
3. When the site has loaded, click the back button on either the browser or the phone
4. The browser won't go back to search results from which you clicked on the AMP link, but instead it will go one site before in history (Google Frontpage)

Correct behavior should be that it brings to only one step back to the results of you search. **This happens only with AMP removal script enabled.**

**Comment by TPS** [comment]
Duplicates #1?
