### ISSUE TITLE
User filter for amp does nothing

### ISSUE THREAD

**Issue by d0x360** [AdguardTeam/DisableAMP#50]
I can't even get it to remove "/amp"

**Comment by tvinzz** [comment]
Disable-AMP [v1.0.26](https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.user.js) released.
amp redirect is fixed.
I'm closing this issue. If the problem occurs again, please feel free to reopen.

**Comment by d0x360** [comment]
I got this one today from the Google now feed.

https://amp.thehackernews.com/thn/2021/09/protonmail-shares-activists-ip-address.html

**Comment by tvinzz** [comment]
@d0x360, thank you, it will be fixed on next release.
