### ISSUE TITLE
Бесконечный редирект на страницах Яндекса

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/DisableAMP#51]
Привет,

после последнего обновления теперь бесконечный редирект на этих urlах:
https://yandex.ru/news/
https://yandex.ru/maps/org/papa_dzhons/1020351163/?ll=37.457987%2C55.777758&z=17

Конфигурация:
macOS 11.5.2 Big Sur, Safari 14.1.2, AdGuard для Mac 2.5.3

Фильтры:
Базовый фильтр AdGuard + Фильтр мобильной рекламы + Фильтр счётчиков и систем аналитики + Фильтр виджетов социальных сетей + Фильтр раздражителей + Русский фильтр + Фильтр отслеживания по URL + AdGuard Extra + Disable AMP (версия скрипта 1.0.24)

Спасибо.

**Comment by tvinzz** [comment]
@ammnt, thank you for your report.
Hotfix will come pretty soon.

**Comment by tvinzz** [comment]
@ammnt, problem fixed and new released [v1.0.25](https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.user.js) published.
If the problem occurs again, feel free to reopen issue.
