### ISSUE TITLE
Auto clicking first Google result when extension is enabled

### ISSUE THREAD

**Issue by Miteirao** [AdguardTeam/DisableAMP#56]
Search any term and you can't scroll the results page because it auto clicks on the first.

The same occurs with @bentasker RemoveAMP Google Search script

Another request for Adguard js: remove `google/amp/` from the middle of URLs. Example: `https://ge.globo.com/google/amp/futebol/times/atletico-mg/noticia/finalista-da-copa-do-brasil-2021-atletico-mg-tem-mais-r-23-milhoes-garantidos-em-premiacao.ghtml`

Android 11, Firefox 93.2.0 + Google Search Fixer extension

**Comment by bastele7** [comment]
I have the same problem and get the error message "Redirect blocked" from Chrome.

**Comment by Miteirao** [comment]
So @tvinzz, no solution?

**Comment by freman** [comment]
I just updated https://github.com/AdguardTeam/DisableAMP/issues/60 with a screenshot from the console if it helps

**Comment by stanislav-atr** [comment]
@Miteirao, hi! Solution is being reviewed rn, and i am going to copy second request to [another issue.](https://github.com/AdguardTeam/DisableAMP/issues/61)
