### ISSUE TITLE
Redirection does not work for yandex turbo page

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/DisableAMP#58]
Добрый вечер,

https://yandex.ru/turbo/peopletalk.ru/s/article/oni-vstrechayutsya-kane-uest-zamechen-na-svidanii-s-dzhuliej-foks/
с этого URL не срабатывает переадресация на исходную страницу:

https://peopletalk.ru/article/oni-vstrechayutsya-kane-uest-zamechen-na-svidanii-s-dzhuliej-foks/

Спасибо.

**Comment by jellizaveta** [comment]
Здравствуйте. Исправления в новой версии, спасибо за ваш репорт!
