### ISSUE TITLE
Unexpected redirect to the first search result

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/DisableAMP#60]
### Issue URL (Incorrect Blocking)
 [https://google.com/search?q=amp](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fgoogle.com%2Fsearch%3Fq%3Damp)
### Comment
Username: @psydvl
> При включении расширения "Отключение AMP" в поиске Google происходит переадресация на первый amp сайт в выдаче. 
> На приложенных скриншотах я не нажимал ничего для перехода с первого на второй. 
> URL расширения из описания https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Tk2J86u.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/qaVTSjK.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Расширение Отключить AMP
Browser: | Firefox Mobile
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>AdGuard Experimental, <br/>Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/>AdGuard Russian

**Comment by freman** [comment]
Can confirm this is happening in Chrome also on Android
![image](https://user-images.githubusercontent.com/506680/150063240-f05d867e-c13a-418a-a0f1-3c46b188de22.png)

**Comment by stanislav-atr** [comment]
Is being resolved [here](https://github.com/AdguardTeam/DisableAMP/issues/61).
