### ISSUE TITLE
Remove google/amp/ from the middle of URLs

### ISSUE THREAD

**Issue by stanislav-atr** [AdguardTeam/DisableAMP#61]
@Miteirao: 

Another request for Adguard js: remove google/amp/ from the middle of URLs. Example: https://ge.globo.com/google/amp/futebol/times/atletico-mg/noticia/finalista-da-copa-do-brasil-2021-atletico-mg-tem-mais-r-23-milhoes-garantidos-em-premiacao.ghtml

Android 11, Firefox 93.2.0 + Google Search Fixer extension

**Comment by jellizaveta** [comment]
@Miteirao Hello. With the latest version of disable-amp — 1.0.52 the page redirects correctly to the classic HTML version. Could you please check if the issue resolved on your end?

**Comment by Miteirao** [comment]
> @Miteirao Hello. With the latest version of disable-amp — 1.0.52 the page redirects correctly to the classic HTML version. Could you please check if the issue resolved on your end?

Yes, it's correct now.
