### ISSUE TITLE
Редирект с субдоменов *.turbopages.org

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/DisableAMP#62]
Здравствуйте,

возможно ли добавить также автоматическую переадресацию с поддоменов *.turbopages.org?

Например:
https://ria-ru.turbopages.org/ria.ru/s/20210615/inostrantsy-1737064338.html
на
https://ria.ru/s/20210615/inostrantsy-1737064338.html

Спасибо.

**Comment by ammnt** [comment]
За месяц определились, что это "question"😅

**Comment by stanislav-atr** [comment]
@ammnt, добрый день! С какой страницы делали переход на `https://ria-ru.turbopages.org/ria.ru/s/20210615/inostrantsy-1737064338.html`?

**Comment by ammnt** [comment]
@stanislav-atr, ну я уже не найду спустя почти два месяца откуда был переход. Скорее всего, из результатов поиска Яндекса.

**Comment by maximtop** [comment]
@stanislav-atr забей в яндексе swift site:ria.ru
