### ISSUE TITLE
Websites reloading continuously

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/DisableAMP#65]
@kamharry commented on [Sat Feb 12 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4108)

Many of the sites are reloading continuously like reload loop and not able to explore the content with adguard turned on, after disabling adguard the problem is solved.
Please look into this.

---

@Chinaski1 commented on [Mon Feb 14 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4108#issuecomment-1038884059)

Hello!

Judging by symptoms I would venture to guess that you accidentally turn stealth-mode on the ultimatum level.
Is the issue only reproduced on certain sites? What browser are you using?

Could you please send an email to support@adguard.com directly from the AdGuard application?
AdGuard - Settings -> Support -> Send feedback -> Other (Leave `Send detailed system info` enabled)

---

@kamharry commented on [Tue Feb 15 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4108#issuecomment-1039818004)

Stealth mode is off from the beginning because I don't like it as it causes issues in login with some apps and sites..
Browser - Google Chrome And Brave

---

@Chinaski1 commented on [Tue Feb 15 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4108#issuecomment-1040088626)

Please specify the number of the request to the helpdesk so I can find your log.
The request number should be emailed to you after the logs are sent.
Something like that: 573980

---

@kamharry commented on [Tue Feb 15 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4108#issuecomment-1040090569)

578549

---

@kamharry commented on [Tue Feb 15 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4108#issuecomment-1040113749)

Turning off Disable Amp userscript in extensions solved the issue on many site 

---

@Chinaski1 commented on [Tue Feb 15 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4108#issuecomment-1040115548)

Can you send me some examples of sites where the issue is reproduced?
I will check and move the task to the appropriate repository.

---

@kamharry commented on [Tue Feb 15 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4108#issuecomment-1040117124)

https://newsupdate.uk/snapdragon-695-vs-680-vs-mediatek-dimensity-810-performance-comparison-best-under-rs-20k-91mobiles-com/amp/

https://sparrowsnews.com/2022/02/08/xiaomi-l1-mega-cup-flagship-exposure/amp/

---

@kamharry commented on [Tue Feb 15 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4108#issuecomment-1040117796)

These are the 2 sites which i opened now and they are reloading in loop i guess the issue is the amp !

**Comment by Chinaski1** [comment]
@tvinzz please take a look

**Comment by Chinaski1** [comment]
@kamharry

Please specify which [version](https://uploads.adguard.com/Chinaski29wj7.png) of Disable AMP you are using?

**Comment by kamharry** [comment]
1.0.34

**Comment by ameshkov** [comment]
These websites seem to simply always redirect mobile users to AMP versions, they just don't want the users to see the normal page:(

For now, the only solution I see is to keep the information about redirect in the `sessionStorage` and stop redirecting to the canonical page when this behavior is detected.

**Comment by kamharry** [comment]
How to do that ?

**Comment by ameshkov** [comment]
That's on us to fix.

**Comment by kamharry** [comment]
Oh okay sir

Thankyou for responding.

**Comment by AdamWr** [comment]
It seems that the same problem occurs on these websites:
https://github.com/AdguardTeam/AdguardFilters/issues/113807 - [http://winaero.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwinaero.com%2F)
https://github.com/AdguardTeam/AdguardFilters/issues/113946 - [https://menworld.pl/genesis-thor-660-recenzja/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://menworld.pl/genesis-thor-660-recenzja/)

**Comment by stanislav-atr** [comment]
@kamharry, hi! The issue was solved and new version of DisableAMP was deployed, please, [update your userscript](https://github.com/AdguardTeam/DisableAMP#how-to-install).

**Comment by stanislav-atr** [comment]
@kamhur, what version are u using right now?

**Comment by stanislav-atr** [comment]
@kamharry, the new version we've just deployed is 1.0.35, please, update manually with the link i provided above.

**Comment by kamharry** [comment]
Updated sir

**Comment by kamharry** [comment]
Issue is resolved...
Thankuh for replying

**Comment by stanislav-atr** [comment]
@kamharry, provide the websites so i can test it, please.

**Comment by kamharry** [comment]
https://menworld.pl/genesis-thor-660-recenzja/
https://menworld.pl/test-sonos-beam-gen-2-czy-warto-placic-za-soundbar/?amp=1
https://sparrowsnews.com/2022/03/27/samsung-galaxy-diamond-exposure/amp/

**Comment by stanislav-atr** [comment]
@kamharry, i dont experience such behaviour on my device, try cleaning browser cache.

**Comment by kamharry** [comment]
Fixed 👍🏻
