### ISSUE TITLE
Long-standing issue.

### ISSUE THREAD

**Issue by f1vefour** [AdguardTeam/DisableAMP#71]
Not only is disable amp failing on many sites I have to disable Adguard or I simply get a white page.

This mess of a URL comes from clicking links from Google news feed on a Pixel device.

Example: https://www-wlbt-com.cdn.ampproject.org/v/s/www.wlbt.com/2022/08/07/more-human-remains-discovered-drought-dries-lake-mead/?amp_gsa=1&amp_js_v=a9&outputType=amp&usqp=mq331AQIKAGwASCAAgM%3D#amp_tf=From%20%251%24s&aoh=16599760950816&csi=0&referrer=https%3A%2F%2Fwww.google.com&ampshare=https%3A%2F%2Fwww.wlbt.com%2F2022%2F08%2F07%2Fmore-human-remains-discovered-drought-dries-lake-mead%2F

**Comment by maximtop** [comment]
Which version of DisableAMP are you using?

**Comment by f1vefour** [comment]
Sorry, it's whatever is in Adguard 4.0 nightly 35

**Comment by maximtop** [comment]
Can you tell me which version of DisableAMP is used there? 
It can be found in AdGuard app: Settings -> Extensions -> Disable AMP

**Comment by f1vefour** [comment]
v1.0.35

**Comment by maximtop** [comment]
I've opened your URL on my phone and it redirected me to the version without the amp. Do I correctly understand that the problem was that this URL is not redirected on your device?

**Comment by f1vefour** [comment]
Correct, I will go through the filters and see if I can find which is causing the issue.

If it's working for you it must be one of them.

**Comment by f1vefour** [comment]
Found the issue, it's Dandelion Sprout's Annoyances List, closing.

Thank you for your assistance.

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList
