### ISSUE TITLE
Wrong redirect path

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/DisableAMP#73]
Hello,

this URL:
https://www.google.com/amp/s/www.mos.ru/amp/otvet-dokumenti/kak-pomenyat-ili-vosstanovit-attestat-ili-diplom/
redirected to:
https://www.mos.ru/static/images/favicon/favicon.ico
but has to be:
https://www.mos.ru/otvet-dokumenti/kak-pomenyat-ili-vosstanovit-attestat-ili-diplom/

Please see what is wrong!🫠

Thank you.
Best regards!

**Comment by tvinzz** [comment]
@ammnt 
It's a website issue and not related to DisableAMP.
Please try to open the link without userscript and you will see wrong redirect as well.
