### ISSUE TITLE
AMP pages in Google Images search results and Google news are not disabled.

### ISSUE THREAD

**Issue by Githubmaniak** [AdguardTeam/DisableAMP#80]
I'm using Android 10 and Firefox Nightly 119.0a1 and I installed AdGuard AMP disabling on tampermonkey, but it didn't disable AMP pages.

The URL in question is:
https://www.google.com/amp/s/www.goo-net.com/pit/amp/shop/0207339/blog/98265

**Comment by alexx7311** [comment]
@Githubmaniak We couldn't reproduce the problem. This userscript doesn't disable AMP pages, it opens them, but without AMP. Please make a screen recording of you installing the script and then testing it on the page you mentioned.

**Comment by Githubmaniak** [comment]
@alexx7311 https://youtube.com/shorts/_siuxyx_tJQ?si=xyDXFW9X9lqakRPV

I have installed the script but haven't activated it.  So, when shooting the video, I activated it briefly and filmed it. As you can see in the video, when you press the "Visit" button, the amp layout (?) pops up.

**Comment by alexx7311** [comment]
@Githubmaniak YouTube says the video is private.

**Comment by Githubmaniak** [comment]
After confirmation, I changed the video's privacy settings.

https://youtube.com/shorts/_siuxyx_tJQ?si=mZ8Y9hYv9bavqfXI

You will now be able to play the video.  Perhaps the settings were
incorrect when uploading the video.  sorry.

2023년 10월 5일 (목) 오후 5:31, alexx7311 ***@***.***>님이 작성:

**Comment by alexx7311** [comment]
@Githubmaniak Thanks! Please send us the full link you are trying to access the site from (Google search link).

**Comment by Githubmaniak** [comment]
https://www.google.com/search?client=firefox-b-m&sca_esv=571342877&sxsrf=AM9HkKm5NorxqsPRLDrzuQAOI_sa4QwLDA:1696613390330&q=%E3%83%8F%E3%83%AA%E3%82%A2%E3%83%BC30%E7%B3%BB%E3%83%93%E3%83%BC%E3%83%88%E3%82%BD%E3%83%8B%E3%83%83%E3%82%AF&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjMl86z-eGBAxU3m1YBHR_vAsMQ0pQJegQICxAB&biw=414&bih=722&dpr=2.61#imgrc=wNlrVezNG8ddhM

**Comment by stanislav-atr** [comment]
@Githubmaniak, this website is rendering its entire content in a subframe, and Disable AMP does not yet handle such cases. This may change in the future, if more cases come up.
