### ISSUE TITLE
Some pages are not redirecting from AMP to HTML.

### ISSUE THREAD

**Issue by Githubmaniak** [AdguardTeam/DisableAMP#81]
Disable AMP does not work in the following URLs:

https://www.fnnews.com/ampNews/202310292340416933?amp_js_v=0.1&usqp=mq331AQIUAKwASCAAgM%3D 

https://m.yna.co.kr/amp/view/AKR20231027076900005?amp_js_v=0.1 

https://www.joongang.co.kr/amparticle/25203054?amp_js_v=0.1 

https://www.fnnews.com/ampNews/202310292340416933?amp_js_v=0.1&usqp=mq331AQIUAKwASCAAgM%3D 

https://m.yna.co.kr/amp/view/AKR20231027076900005?amp_js_v=0.1 

https://www.joongang.co.kr/amparticle/25203054?amp_js_v=0.1 

https://www.mediatoday.co.kr/news/articleViewAmp.html?idxno=313292 

https://m.khan.co.kr/opinion/column/article/202310242027005/amp?amp_js_v=0.1

Those URLs will not redirect to HTML and will remain AMP.

**Comment by alexx7311** [comment]
@Githubmaniak Hello! We would need Google search links for these pages.

**Comment by Githubmaniak** [comment]
@alexx7311 
https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.fnnews.com/ampNews/202310292340416933&ved=2ahUKEwjTkIOIhqKCAxUIG4gKHb6GBIAQFnoECBAQAQ&usg=AOvVaw3-es5YjSckkcQWkH621myT

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://m.yna.co.kr/view/AKR20231027076900005&ved=2ahUKEwiJsKGphqKCAxWxcfUHHcPQAu8QFnoECBEQAQ&usg=AOvVaw39oggyW9ell9iuILc_tyJt

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.joongang.co.kr/amparticle/25203054&ved=2ahUKEwi41prGhqKCAxVWed4KHWkrB9EQFnoECAwQBQ&usg=AOvVaw3Nq96c1rwmzXohfp1vNYBF

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=http://www.mediatoday.co.kr/news/articleView.html%3Fidxno%3D313292&ved=2ahUKEwj6iZbuhqKCAxWVMN4KHUIgDx4QFnoECAwQAQ&usg=AOvVaw2teOb3NXdEWstjwSzRQ9Ot

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://m.khan.co.kr/opinion/column/article/202310242027005/amp&ved=2ahUKEwjq58SQh6KCAxWVGIgKHRXeB9wQFnoECA4QAQ&usg=AOvVaw3YIeKTtDb0wx78gESPM0gX

I noticed that some URLs are duplicates.  Above is the Google search result URL, including duplicate URLs.

**Comment by alexx7311** [comment]
@Githubmaniak These aren't exactly the links we need. Please send us a link from Google search with the search results. It would also be helpful if you could attach a screenshot of the element you are clicking on.
<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/DisableAMP/assets/114913601/9f0cac9c-8672-40c1-bb9b-8d1ae748d5d6)
</details>

**Comment by stanislav-atr** [comment]
@Githubmaniak hi! Thank you for you feedback, fix is one the way.
