### ISSUE TITLE
Disable AMP filter bug

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/DisableAMP#82]
hi, when I enable Disable AMP, then if i click any amp url then it first loads amp page then the page refreshes and loads the page without amp. here is the amp url

https://www-hindustantimes-com.cdn.ampproject.org/v/s/www.hindustantimes.com/india-news/gujarat-high-court-dismisses-delhi-cm-s-plea-on-pm-modi-s-degree-disclosure-101699533359384-amp.html?amp_gsa=1&amp_js_v=a9&usqp=mq331AQGsAEggAID#amp_tf=From%20%251%24s&aoh=16995386077380&csi=0&referrer=https%3A%2F%2Fwww.google.com&ampshare=https%3A%2F%2Fwww.hindustantimes.com%2Findia-news%2Fgujarat-high-court-dismisses-delhi-cm-s-plea-on-pm-modi-s-degree-disclosure-101699533359384.html

now you click at your end and see for your self that it opens this amp page first then the page refreshes and loads the page without amp Could you improve the Disable AMP filter, so that it opens only non amp page. waiting for this fix thank you

**Comment by stanislav-atr** [comment]
@rajatmathurs hi! Thank you for feedback, could you also give me the link to the origin of this url, i.e the website where you click on such amp urls, please?

**Comment by rajatmathurs** [comment]
> @rajatmathurs hi! Thank you for feedback, could you also give me the link to the origin of this url, i.e the website where you click on such amp urls, please?

@stanislav-atr hi, this amp link problem is there in Google app, just open the Google app and click on any news feeds link from scrolling down, when you click any news feed link then first the amp page opens and then page refreshes to load non amp page.. I have  already give the amp link above for your reference and if you click this above link then it opens in my Chrome browser first as amp page then it refreshes to load non amp page in my Chrome browser. You could also copy the amp url from the Google app and open in Chrome browser to see the problem.

**Comment by stanislav-atr** [comment]
@rajatmathurs, Disable AMP cannot modify URLs within apps. The redirect feature was added to specifically address such cases. Unfortunately, there is nothing that can be done in this situation.
