### ISSUE TITLE
Please update locales.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/DisableAMP#9]
Please update locales.
https://crowdin.com/translate/adguard-applications/17462/en-zhtw

Thanks.

**Comment by ameshkov** [comment]
Hm, I've downloaded new strings, but I see no difference

**Comment by ameshkov** [comment]
Please check what's wrong here:
https://github.com/AdguardTeam/DisableAMP/blob/master/locales/zh-TW/messages.json

**Comment by lancelot-moon** [comment]
From that link, it shows you updated the translation on 17 Oct 2019.
But it's still old translation in AG for Android app.
Maybe it's because the version of DisableAMP script is never updated during the period.

**Comment by ameshkov** [comment]
Hmmm

**Comment by ameshkov** [comment]
You're right indeed

**Comment by lancelot-moon** [comment]
I see the latest version of DisableAMP script is v1.0.5.
https://github.com/AdguardTeam/DisableAMP/releases

But it's still v1.0.4 with old locales in AG for Android app.
Do you not release DisableAMP script v1.0.5?

**Comment by ameshkov** [comment]
Please check it now, it should've been published already

**Comment by lancelot-moon** [comment]
Yes, fixed in v1.0.5.
Thanks a lot!
