### ISSUE TITLE
The amp tag isn't removed from the link

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/DisableAMP#90]
https://github.com/AdguardTeam/AdguardForAndroid/issues/5177

**Comment by alexx7311** [comment]
@Spok1 Здравствуйте! Если по шагам следовать, что вы описали, то и не должен тег удалиться. Disable AMP работает только на странице поиска Google. То есть если вы с поисковика гугла переходите, то уже быть amp не должно, а если просто ссылку открывать, то откроется с amp.

Вы из поисковика переходите или нет?

**Comment by Spok1** [comment]
@alexx7311, как бы и через Гугл новости попадается, и в новостной ленте оперы, и что там,что там—амп не убирается. Хотя вы мне ответили в другом коммите,что только из поисковой машины гугл,хотя это в корне не так: из новостной ленты оперы ссылки с амп также убираются отлично,а вот с этого не хочет.

**Comment by alexx7311** [comment]
@Spok1 Может он где-то еще и убирает, но мы делали его только для гугла, это и в описании скрипта есть. Я увидел задачу по ссылкам с Google News, там ответил, а эту задачу закрываем.
