### ISSUE TITLE
The amp tag isn't removed from Opera news feed link

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/DisableAMP#91]
Не убирается метка с юрл https://www.dialog.ua/opinion/289496_1707147156/amp

Ссылка для перехода через новостную ленту браузера опера: http://opr.news/8f06f42240205ru_ua?link=1&client=opera

**Comment by alexx7311** [comment]
@Spok1 Здравствуйте! Disable AMP работает только с Google search.

**Comment by Spok1** [comment]
@alexx7311,а почему так?
