### ISSUE TITLE
AMP links on Google News page is not removed

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/DisableAMP#93]
При переходе из «_**новостей гугл**_» амп не убирается ни с прямым переходом путём копирования и вставки юрл в новой вкладки,ни с переходом по ссылке,которая располагается в правом верхнем углу упрощённого просмотра статьи.

1. [Статья](https://news.google.com/articles/CBMiMWh0dHBzOi8vd3d3LmJiYy5jb20vcnVzc2lhbi9hcnRpY2xlcy9jejkzMDZwbDVrNm_SATVodHRwczovL3d3dy5iYmMuY29tL3J1c3NpYW4vYXJ0aWNsZXMvY3o5MzA2cGw1azZvLmFtcA?hl=ru&gl=UA&ceid=UA%3Aru)
2. [Статья](https://news.google.com/articles/CBMif2h0dHBzOi8vZWFkYWlseS5jb20vcnUvbmV3cy8yMDI0LzAyLzIxL3Ytb2Rlc3NlLWktbmlrb2xhZXZlLXZvZW5rb215LW90a3J5bGktbmFzdG95YXNoY2h1eXUtb2hvdHUtbmEtbXV6aGNoaW4tZGVwdXRhdC1iYXJiYXNob3bSAYIBaHR0cHM6Ly9lYWRhaWx5LmNvbS9ydS9hbXBuZXdzLzIwMjQvMDIvMjEvdi1vZGVzc2UtaS1uaWtvbGFldmUtdm9lbmtvbXktb3RrcnlsaS1uYXN0b3lhc2hjaHV5dS1vaG90dS1uYS1tdXpoY2hpbi1kZXB1dGF0LWJhcmJhc2hvdg?hl=ru&gl=UA&ceid=UA%3Aru)
3. [Статья](https://news.google.com/articles/CBMiTGh0dHBzOi8vd3d3LnJiYy51YS91a3IvbmV3cy9vZGVza2l5LW9ibGFzdGktcHJvbHVuYWxpLXZpYnVoaS0xNzA4NTQwOTM0Lmh0bWzSAVBodHRwczovL3d3dy5yYmMudWEvdWtyL25ld3Mvb2Rlc2tpeS1vYmxhc3RpLXByb2x1bmFsaS12aWJ1aGktMTcwODU0MDkzNC5odG1sL2FtcA?hl=ru&gl=UA&ceid=UA%3Aru)
4. [Статья](https://news.google.com/articles/CBMiNmh0dHBzOi8vd3d3LnByYXZkYS5jb20udWEvcnVzL25ld3MvMjAyNC8wMi8xOS83NDQyNjM1L9IBP2h0dHBzOi8vd3d3LnByYXZkYS5jb20udWEvcnVzL25ld3MvMjAyNC8wMi8xOS83NDQyNjM1L2luZGV4LmFtcA?hl=ru&gl=UA&ceid=UA%3Aru)

**Comment by alexx7311** [comment]
@Spok1 Здравствуйет! Мы недавно пофиксили баг, из-за которого на новостной страницы гугла скрипт не отрабатывал, как нужно.
Как только сборка появится, я напишу в этой задаче.

**Comment by alexx7311** [comment]
@Spok1 Проверьте, пожалуйста, убирается ли AMP из новостей гугла на [стабильной версии 1.0.47](https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.user.js)

**Comment by Spok1** [comment]
@alexx7311, из этих ссылок нет. Потом проверю,убираются ли из агрегатора.

**Comment by alexx7311** [comment]
@Spok1 Из этих ссылок не будет убираться. Посмотрите, пожалуйста, именно на news.google.com

**Comment by alexx7311** [comment]
@Spok1, пока не получилось проверить?

**Comment by Spok1** [comment]
@alexx7311, нашёл эти статьи с указанных доменов. Что могу рассказать! После обновлений в механизме убирания амплификатора из юрл,после открытия ссылки с ленты гугл сразу перенаправляет на 
чистую страницу без меток,а раньше появлялась станица предпросмотра от Гугл,а после нужно было вручную переходить по ссылке,и то, она игнорировалась скриптом и очищение не происходило. Благодарю за хорошо проделанную работу.
