### ISSUE TITLE
Disable AMP does not work on some Korean newspapers' AMP pages.

### ISSUE THREAD

**Issue by Githubmaniak** [AdguardTeam/DisableAMP#98]
https://www.google.com/search?sxsrf=ADLYWIL8brFILg2Fme3O3DkIXVo8y9Ubnw:1723439982446&q=site:biz.chosun.com&tbm=nws&fbs=AEQNm0BKIkCUOVTN3icH4GfXZ2M30mAHZMphfzslgiOJVDt-aCcAL9A-1GE6vetsBKwOH6KDF0wxbLl7AnrcJrTiRsEcI1cqS1hCniB5N-U1KgbrDH3c7-yMsVWQ3yzSnLG6bZT-R8MmNqKFVel3y9K_bDnhOxLWD1_vqUSXwdLM5XgziJfHUZ2fQUibua7SBJzCo0FxoZg9rRDvGCOzd3fx1V00aYfBRw&dpr=2.63

https://www.google.com/search?sxsrf=ADLYWIJMCtvXWz3uv2rgTD-Pc6aZnvgzdg:1723440155258&q=site:fnnews.com&tbm=nws&fbs=AEQNm0BKIkCUOVTN3icH4GfXZ2M30mAHZMphfzslgiOJVDt-aCcAL9A-1GE6vetsBKwOH6KDF0wxbLl7AnrcJrTiRsEcI1cqS1hCniB5N-U1KgbrDH3c7-yMsVWQ3yzSnLG6bZT-R8MmNqKFVel3y9K_bDnhOxLWD1_vqUSXwdLM5XgziJfHUZ2fQUibua7SBJzCo0FxoZg9rRDvGCOzd3fx1V00aYfBRw&dpr=2.63

Disable AMP does not work on both Chosun Ilbo and Fnnews.

**Comment by Githubmaniak** [comment]
https://www.google.com/search?sxsrf=ADLYWILv5dYoZEU6x3D_IvJOKKBGCT0s5Q:1723440766119&q=site:khan.co.kr&tbm=nws&fbs=AEQNm0BKIkCUOVTN3icH4GfXZ2M30mAHZMphfzslgiOJVDt-aCcAL9A-1GE6vetsBKwOH6KDF0wxbLl7AnrcJrTiRsEcI1cqS1hCniB5N-U1KgbrDH3c7-yMsVWQ3yzSnLG6bZT-R8MmNqKFVel3y9K_bDnhOxLWD1_vqUSXwdLM5XgziJfHUZ2fQUibua7SBJzCo0FxoZg9rRDvGCOzd3fx1V00aYfBRw&dpr=2.63

**Comment by alexx7311** [comment]
@Githubmaniak, hello! I couldn't reproduce the problem. Are you using userscript manager or AdGuard? What browser are you using?

**Comment by Githubmaniak** [comment]
@alexx7311 I'm using Kiwi Browser and AdGuard.

MoneyToday disable amp doesn't work either.

https://www.google.com/search?sxsrf=ADLYWILLwsayS5-oPCussZka1MgObKU1jA:1724133301220&q=%EB%A8%B8%EB%8B%88%ED%88%AC%EB%8D%B0%EC%9D%B4&tbm=nws&fbs=AEQNm0Bp0ACmxjRhB77tSBrdCVamzDvebEt-JfC4qHT7aHadYgkAPtXVHf6MWuaEiD1w3PUeEDxQqpcnThy3tp9n8mFfybMZte8S_lLA-s2OgOFD-wCDwftreB2Ye2az9IQEGNCzejGarkalNJ4J5Qju-xpqjGgbsOdkj1m-1Td79B7bixbvz8tsb--MwKlBg9XhYo7_ir2x3UoPtN8ftC9340XMdy98BG7HrqO-QFK4NXCyek_03XI&dpr=2.63

**Comment by Githubmaniak** [comment]
https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.newsian.co.kr%2Fnews%2Fphoto%2F202010%2F43822_22023_3124.jpg&tbnid=VavnmmTqYta1DM&vet=1&imgrefurl=http%3A%2F%2Fwww.newsian.co.kr%2Fnews%2FarticleView.html%3Fidxno%3D43822&docid=vcDTftcZ0AJopM&w=960&h=319&source=sh%2Fx%2Fim%2Fm4%2F2&kgs=417477040bda5546&shem=abme%2Ctrie#vhid=VavnmmTqYta1DM&vssid=mosaic

newsian doesn't work either.
